### PR TITLE
Added WebApi-filter and sample-project to catch WebApi-exceptions

### PR DESCRIPTION
**Pull request by itssimple**
Additional setup to handle WebApi-exceptions:
In `~/App_Start/WebApiConfig.cs`, add:
`config.Filters.Add(new StackExchange.Exceptional.WebApi.WebAPIExceptionHandlerAttribute());`

The WebApi-extension requires at least .NET 4.5

#74 can be closed, since SOAP is deprecated

### CODE REVIEW

**Comment by NickCraver** [comment]
This adds a lot more porting to .NET Core weight in the coming weeks - I'd much rather wait until after that's done before such an addition. Also: while it may seem minor, you ignored the /packages folder which is a huge dependency change, and creates a large dependency list for builds.

**Comment by itssimple** [comment]
Ah, of course. I missed the v2-branch.

Yeah, I wasn't sure if I was supposed to include the packages folder. Habit from work.
I'll fix the .gitignore again. Sorry.

**Comment by itssimple** [comment]
I cannot open the solution in VS15 after a reload.
It gets stuck while initializing Samples.Console and never finishes.
No error messages or anything, it just freezes.

Closing the request until I sort this out.

**Comment by itssimple** [comment]
If I remove all packages before I open the solution, it works. But after successful build and reload, it gets stuck on initializing.

No clue what the problem is in this case.

**Comment by chyredwan** [comment]
Hi, understand this is deprecated. But is there any other extension for WebApi logging? Apprentice your advice.

**Comment by itssimple** [comment]
If you are using .NET Core, you can use a middleware to handle exceptions in an WebApi.

**Comment by chyredwan** [comment]
Hi,

Thanks. We are using .net WebApi

Sent from my iPhone


[https://www.posturite.co.uk/media/email-images/email-signature/posturite-logo-signature.png]   Redwan Chowdhury
.Net Developer

redwan@workrite.co.uk
Posturite Ltd, The Mill, Berwick, East Sussex BN26 6SZ, UK
Registered in England and Wales, No. 2574809
posturite.co.uk<https://www.posturite.co.uk>
[https://www.posturite.co.uk/media/email-images/email-signature/facebook-icon-signature.png]<https://www.facebook.com/posturiteltd/>  [https://www.posturite.co.uk/media/email-images/email-signature/linkedin-icon-signature.png] <https://www.linkedin.com/company/posturite-ltd/>   [https://www.posturite.co.uk/media/email-images/email-signature/twitter-icon-signature.png] <https://twitter.com/posturite>   [https://www.posturite.co.uk/media/email-images/email-signature/google-plus-signature.png] <https://plus.google.com/+posturite>   [https://www.posturite.co.uk/media/email-images/email-signature/youtube-icon-signature.png] <https://www.youtube.com/user/Posturite>
[https://www.posturite.co.uk/media/email-images/email-signature/meet-oploft-banner.jpg] <https://www.posturite.co.uk/product/oploft?utm_source=signature&utm_medium=email&utm_campaign=oploft>
[https://www.posturite.co.uk/media/email-images/email-signature/leaf.png] Please consider the environment before printing this email.

On 7 Nov 2019, at 14:24, Chris Gårdenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


If you are using .NET Core, you can use a middleware to handle exceptions in an WebApi.

**Pull request closed without merging**
