### PR TITLE
Port docs to Jekyll

### PR DESCRIPTION
**Pull request by mmillican**
The docs will likely need an overhaul for v2, but figured it would be helpful to port the docs to Jekyll and structure similar to MiniProfiler.

I ported the readme, Initial and SQL setup docs mostly as-is so far, with a few formatting changes, etc.

Happy to help update as necessary.

### CODE REVIEW

**Comment by NickCraver** [comment]
Merged in, thanks! I'll see what GitHub does with the pages here since I also have pages under my account...may be a bit trickier.

**Comment by mmillican** [comment]
Sounds good, let me know if I need to change anything.

**Comment by NickCraver** [comment]
@mmillican got it spun up with Jekyll locally and fixed up the bits - now live at https://nickcraver.com/StackExchange.Exceptional/

**Comment by mmillican** [comment]
Nice!  Looks good to me.  Not sure how much configuration related things will change, but I was thinking I could start documenting those next.  Thoughts?

**Comment by NickCraver** [comment]
I'd hold off on those - I really need to figure out how the GetCustomData works...and that may mean everything going static, or inheriting per child or something else...may change every single call indeed.

**Pull request merged**
