### PR TITLE
fix race condition

### PR DESCRIPTION
**Pull request by jpuck**

### CODE REVIEW

**Comment by jpuck** [comment]
not really sure why the build failed - I only changed the README

**Comment by CptRobby** [comment]
I think there's something wrong with AppVeyor or something because it has been failing on all of the recent pull requests.

I see the one typo that you fixed (and I can't tell why git thinks the other line changed). But why did you call the pull request "fix race condition"??

**Comment by CptRobby** [comment]
Um...If you say so! :droplet: :awkward_laugh:
I hope you realize though that "race condition" means something **completely different** in programming. :stuck_out_tongue_winking_eye:

**Comment by jpuck** [comment]
in deed, I'm not as funny as I am inside my own head

**Comment by CptRobby** [comment]
Indeed! I think adding a description that would hint at the joke would have been better. Instead, I was thinking that something must have been missed in the commit that would have fixed an actual race condition. So I was expecting you to append the missing changes to the request, but instead you commented about it only being a change to the readme file, which just made me scratch my head. LOL :smiley:

**Comment by NickCraver** [comment]
Thanks!

**Pull request merged**
