### PR TITLE
Update MySqlConnector to version 1.2.0.  Fix usings to use new namespace.

### PR DESCRIPTION
**Pull request by johnboker**
I'm not 100% sure if this will work, I'm not able to run the tests on my machine.

This might also cause other issues if trying to use MySqlConnector < 1.0.0.  Is there a way in a config to change the namespace of a type?

https://mysqlconnector.net/overview/version-history/

### CODE REVIEW

**Comment by NickCraver** [comment]
@bgrainger Any downsides here? I always look to you on upgrading the dependency thoughts - since we'd be downstream and users only load 1, could have the namespace conflicts across usages but that's also an easy fix - cool to upgrade at the dependency level here you think?

**Comment by bgrainger** [comment]
Doing this upgrade makes sense to me; otherwise users (of StackExchange.Exceptional.MySQL) will be locked to a pre-1.0 version of MySqlConnector. Since 1.x has been out for nine months now, I would expect that most users have upgraded, or would want to upgrade.

**Comment by johnboker** [comment]
What I ended up doing for my own use was created a new MySQLErrorStore and just not use the standard one. I think updating this would be good, but also have a MySQLErrorStore-legacy for people who rely on the old connector for some reason.


https://gist.github.com/johnboker/96afe98e0d047ac81d7db3f738b217bf

**Review by NickCraver — APPROVED** [review]
:+1:

**Comment by NickCraver** [comment]
Merging in for the next release (I'll try and get to this soon) - thank you both!

**Pull request merged**
